// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountState int32

const (
	MountState_MOUNT_STATE_UNSPECIFIED     MountState = 0
	MountState_MOUNT_STATE_PENDING_MOUNT   MountState = 1
	MountState_MOUNT_STATE_MOUNTING        MountState = 2
	MountState_MOUNT_STATE_MOUNTED         MountState = 3
	MountState_MOUNT_STATE_PENDING_UNMOUNT MountState = 4
	MountState_MOUNT_STATE_UNMOUNTING      MountState = 5
	MountState_MOUNT_STATE_RETRY_WAIT      MountState = 6
	MountState_MOUNT_STATE_FAILED          MountState = 7
)

// Enum value maps for MountState.
var (
	MountState_name = map[int32]string{
		0: "MOUNT_STATE_UNSPECIFIED",
		1: "MOUNT_STATE_PENDING_MOUNT",
		2: "MOUNT_STATE_MOUNTING",
		3: "MOUNT_STATE_MOUNTED",
		4: "MOUNT_STATE_PENDING_UNMOUNT",
		5: "MOUNT_STATE_UNMOUNTING",
		6: "MOUNT_STATE_RETRY_WAIT",
		7: "MOUNT_STATE_FAILED",
	}
	MountState_value = map[string]int32{
		"MOUNT_STATE_UNSPECIFIED":     0,
		"MOUNT_STATE_PENDING_MOUNT":   1,
		"MOUNT_STATE_MOUNTING":        2,
		"MOUNT_STATE_MOUNTED":         3,
		"MOUNT_STATE_PENDING_UNMOUNT": 4,
		"MOUNT_STATE_UNMOUNTING":      5,
		"MOUNT_STATE_RETRY_WAIT":      6,
		"MOUNT_STATE_FAILED":          7,
	}
)

func (x MountState) Enum() *MountState {
	p := new(MountState)
	*p = x
	return p
}

func (x MountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_api_api_proto_enumTypes[0].Descriptor()
}

func (MountState) Type() protoreflect.EnumType {
	return &file_service_api_api_proto_enumTypes[0]
}

func (x MountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountState.Descriptor instead.
func (MountState) EnumDescriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{0}
}

type MountEventType int32

const (
	MountEventType_MOUNT_EVENT_TYPE_UNSPECIFIED MountEventType = 0
	MountEventType_MOUNT_EVENT_TYPE_SNAPSHOT    MountEventType = 1
	MountEventType_MOUNT_EVENT_TYPE_UPDATED     MountEventType = 2
	MountEventType_MOUNT_EVENT_TYPE_REMOVED     MountEventType = 3
)

// Enum value maps for MountEventType.
var (
	MountEventType_name = map[int32]string{
		0: "MOUNT_EVENT_TYPE_UNSPECIFIED",
		1: "MOUNT_EVENT_TYPE_SNAPSHOT",
		2: "MOUNT_EVENT_TYPE_UPDATED",
		3: "MOUNT_EVENT_TYPE_REMOVED",
	}
	MountEventType_value = map[string]int32{
		"MOUNT_EVENT_TYPE_UNSPECIFIED": 0,
		"MOUNT_EVENT_TYPE_SNAPSHOT":    1,
		"MOUNT_EVENT_TYPE_UPDATED":     2,
		"MOUNT_EVENT_TYPE_REMOVED":     3,
	}
)

func (x MountEventType) Enum() *MountEventType {
	p := new(MountEventType)
	*p = x
	return p
}

func (x MountEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_api_api_proto_enumTypes[1].Descriptor()
}

func (MountEventType) Type() protoreflect.EnumType {
	return &file_service_api_api_proto_enumTypes[1]
}

func (x MountEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountEventType.Descriptor instead.
func (MountEventType) EnumDescriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{1}
}

// Account is used by both requests and responses. Servers must redact
// irods_user_password, irods_ticket, and irods_pam_token before returning a
// MountConfig containing it.
type Account struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	IrodsAuthenticationScheme    *string                `protobuf:"bytes,1,opt,name=irods_authentication_scheme,json=irodsAuthenticationScheme,proto3,oneof" json:"irods_authentication_scheme,omitempty"`
	IrodsClientServerNegotiation *bool                  `protobuf:"varint,2,opt,name=irods_client_server_negotiation,json=irodsClientServerNegotiation,proto3,oneof" json:"irods_client_server_negotiation,omitempty"`
	IrodsClientServerPolicy      *string                `protobuf:"bytes,3,opt,name=irods_client_server_policy,json=irodsClientServerPolicy,proto3,oneof" json:"irods_client_server_policy,omitempty"`
	IrodsHost                    string                 `protobuf:"bytes,4,opt,name=irods_host,json=irodsHost,proto3" json:"irods_host,omitempty"`
	IrodsPort                    int32                  `protobuf:"varint,5,opt,name=irods_port,json=irodsPort,proto3" json:"irods_port,omitempty"`
	IrodsZoneName                string                 `protobuf:"bytes,6,opt,name=irods_zone_name,json=irodsZoneName,proto3" json:"irods_zone_name,omitempty"`
	IrodsClientZoneName          *string                `protobuf:"bytes,7,opt,name=irods_client_zone_name,json=irodsClientZoneName,proto3,oneof" json:"irods_client_zone_name,omitempty"`
	IrodsUserName                string                 `protobuf:"bytes,8,opt,name=irods_user_name,json=irodsUserName,proto3" json:"irods_user_name,omitempty"`
	IrodsClientUserName          *string                `protobuf:"bytes,9,opt,name=irods_client_user_name,json=irodsClientUserName,proto3,oneof" json:"irods_client_user_name,omitempty"`
	IrodsDefaultResource         *string                `protobuf:"bytes,10,opt,name=irods_default_resource,json=irodsDefaultResource,proto3,oneof" json:"irods_default_resource,omitempty"`
	IrodsCwd                     *string                `protobuf:"bytes,11,opt,name=irods_cwd,json=irodsCwd,proto3,oneof" json:"irods_cwd,omitempty"`
	IrodsHome                    *string                `protobuf:"bytes,12,opt,name=irods_home,json=irodsHome,proto3,oneof" json:"irods_home,omitempty"`
	IrodsDefaultHashScheme       *string                `protobuf:"bytes,13,opt,name=irods_default_hash_scheme,json=irodsDefaultHashScheme,proto3,oneof" json:"irods_default_hash_scheme,omitempty"`
	IrodsMatchHashPolicy         *string                `protobuf:"bytes,14,opt,name=irods_match_hash_policy,json=irodsMatchHashPolicy,proto3,oneof" json:"irods_match_hash_policy,omitempty"`
	IrodsEncryptionAlgorithm     *string                `protobuf:"bytes,15,opt,name=irods_encryption_algorithm,json=irodsEncryptionAlgorithm,proto3,oneof" json:"irods_encryption_algorithm,omitempty"`
	IrodsEncryptionKeySize       *int32                 `protobuf:"varint,16,opt,name=irods_encryption_key_size,json=irodsEncryptionKeySize,proto3,oneof" json:"irods_encryption_key_size,omitempty"`
	IrodsEncryptionSaltSize      *int32                 `protobuf:"varint,17,opt,name=irods_encryption_salt_size,json=irodsEncryptionSaltSize,proto3,oneof" json:"irods_encryption_salt_size,omitempty"`
	IrodsEncryptionNumHashRounds *int32                 `protobuf:"varint,18,opt,name=irods_encryption_num_hash_rounds,json=irodsEncryptionNumHashRounds,proto3,oneof" json:"irods_encryption_num_hash_rounds,omitempty"`
	IrodsSslCaCertificateFile    *string                `protobuf:"bytes,19,opt,name=irods_ssl_ca_certificate_file,json=irodsSslCaCertificateFile,proto3,oneof" json:"irods_ssl_ca_certificate_file,omitempty"`
	IrodsSslCaCertificatePath    *string                `protobuf:"bytes,20,opt,name=irods_ssl_ca_certificate_path,json=irodsSslCaCertificatePath,proto3,oneof" json:"irods_ssl_ca_certificate_path,omitempty"`
	IrodsSslVerifyServer         *string                `protobuf:"bytes,21,opt,name=irods_ssl_verify_server,json=irodsSslVerifyServer,proto3,oneof" json:"irods_ssl_verify_server,omitempty"`
	IrodsSslCertificateChainFile *string                `protobuf:"bytes,22,opt,name=irods_ssl_certificate_chain_file,json=irodsSslCertificateChainFile,proto3,oneof" json:"irods_ssl_certificate_chain_file,omitempty"`
	IrodsSslCertificateKeyFile   *string                `protobuf:"bytes,23,opt,name=irods_ssl_certificate_key_file,json=irodsSslCertificateKeyFile,proto3,oneof" json:"irods_ssl_certificate_key_file,omitempty"`
	IrodsSslDhParamsFile         *string                `protobuf:"bytes,24,opt,name=irods_ssl_dh_params_file,json=irodsSslDhParamsFile,proto3,oneof" json:"irods_ssl_dh_params_file,omitempty"`
	IrodsUserPassword            *string                `protobuf:"bytes,25,opt,name=irods_user_password,json=irodsUserPassword,proto3,oneof" json:"irods_user_password,omitempty"`
	IrodsTicket                  *string                `protobuf:"bytes,26,opt,name=irods_ticket,json=irodsTicket,proto3,oneof" json:"irods_ticket,omitempty"`
	IrodsPamToken                *string                `protobuf:"bytes,27,opt,name=irods_pam_token,json=irodsPamToken,proto3,oneof" json:"irods_pam_token,omitempty"`
	IrodsPamTtl                  *int32                 `protobuf:"varint,28,opt,name=irods_pam_ttl,json=irodsPamTtl,proto3,oneof" json:"irods_pam_ttl,omitempty"`
	IrodsSslServerName           *string                `protobuf:"bytes,29,opt,name=irods_ssl_server_name,json=irodsSslServerName,proto3,oneof" json:"irods_ssl_server_name,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_service_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetIrodsAuthenticationScheme() string {
	if x != nil && x.IrodsAuthenticationScheme != nil {
		return *x.IrodsAuthenticationScheme
	}
	return ""
}

func (x *Account) GetIrodsClientServerNegotiation() bool {
	if x != nil && x.IrodsClientServerNegotiation != nil {
		return *x.IrodsClientServerNegotiation
	}
	return false
}

func (x *Account) GetIrodsClientServerPolicy() string {
	if x != nil && x.IrodsClientServerPolicy != nil {
		return *x.IrodsClientServerPolicy
	}
	return ""
}

func (x *Account) GetIrodsHost() string {
	if x != nil {
		return x.IrodsHost
	}
	return ""
}

func (x *Account) GetIrodsPort() int32 {
	if x != nil {
		return x.IrodsPort
	}
	return 0
}

func (x *Account) GetIrodsZoneName() string {
	if x != nil {
		return x.IrodsZoneName
	}
	return ""
}

func (x *Account) GetIrodsClientZoneName() string {
	if x != nil && x.IrodsClientZoneName != nil {
		return *x.IrodsClientZoneName
	}
	return ""
}

func (x *Account) GetIrodsUserName() string {
	if x != nil {
		return x.IrodsUserName
	}
	return ""
}

func (x *Account) GetIrodsClientUserName() string {
	if x != nil && x.IrodsClientUserName != nil {
		return *x.IrodsClientUserName
	}
	return ""
}

func (x *Account) GetIrodsDefaultResource() string {
	if x != nil && x.IrodsDefaultResource != nil {
		return *x.IrodsDefaultResource
	}
	return ""
}

func (x *Account) GetIrodsCwd() string {
	if x != nil && x.IrodsCwd != nil {
		return *x.IrodsCwd
	}
	return ""
}

func (x *Account) GetIrodsHome() string {
	if x != nil && x.IrodsHome != nil {
		return *x.IrodsHome
	}
	return ""
}

func (x *Account) GetIrodsDefaultHashScheme() string {
	if x != nil && x.IrodsDefaultHashScheme != nil {
		return *x.IrodsDefaultHashScheme
	}
	return ""
}

func (x *Account) GetIrodsMatchHashPolicy() string {
	if x != nil && x.IrodsMatchHashPolicy != nil {
		return *x.IrodsMatchHashPolicy
	}
	return ""
}

func (x *Account) GetIrodsEncryptionAlgorithm() string {
	if x != nil && x.IrodsEncryptionAlgorithm != nil {
		return *x.IrodsEncryptionAlgorithm
	}
	return ""
}

func (x *Account) GetIrodsEncryptionKeySize() int32 {
	if x != nil && x.IrodsEncryptionKeySize != nil {
		return *x.IrodsEncryptionKeySize
	}
	return 0
}

func (x *Account) GetIrodsEncryptionSaltSize() int32 {
	if x != nil && x.IrodsEncryptionSaltSize != nil {
		return *x.IrodsEncryptionSaltSize
	}
	return 0
}

func (x *Account) GetIrodsEncryptionNumHashRounds() int32 {
	if x != nil && x.IrodsEncryptionNumHashRounds != nil {
		return *x.IrodsEncryptionNumHashRounds
	}
	return 0
}

func (x *Account) GetIrodsSslCaCertificateFile() string {
	if x != nil && x.IrodsSslCaCertificateFile != nil {
		return *x.IrodsSslCaCertificateFile
	}
	return ""
}

func (x *Account) GetIrodsSslCaCertificatePath() string {
	if x != nil && x.IrodsSslCaCertificatePath != nil {
		return *x.IrodsSslCaCertificatePath
	}
	return ""
}

func (x *Account) GetIrodsSslVerifyServer() string {
	if x != nil && x.IrodsSslVerifyServer != nil {
		return *x.IrodsSslVerifyServer
	}
	return ""
}

func (x *Account) GetIrodsSslCertificateChainFile() string {
	if x != nil && x.IrodsSslCertificateChainFile != nil {
		return *x.IrodsSslCertificateChainFile
	}
	return ""
}

func (x *Account) GetIrodsSslCertificateKeyFile() string {
	if x != nil && x.IrodsSslCertificateKeyFile != nil {
		return *x.IrodsSslCertificateKeyFile
	}
	return ""
}

func (x *Account) GetIrodsSslDhParamsFile() string {
	if x != nil && x.IrodsSslDhParamsFile != nil {
		return *x.IrodsSslDhParamsFile
	}
	return ""
}

func (x *Account) GetIrodsUserPassword() string {
	if x != nil && x.IrodsUserPassword != nil {
		return *x.IrodsUserPassword
	}
	return ""
}

func (x *Account) GetIrodsTicket() string {
	if x != nil && x.IrodsTicket != nil {
		return *x.IrodsTicket
	}
	return ""
}

func (x *Account) GetIrodsPamToken() string {
	if x != nil && x.IrodsPamToken != nil {
		return *x.IrodsPamToken
	}
	return ""
}

func (x *Account) GetIrodsPamTtl() int32 {
	if x != nil && x.IrodsPamTtl != nil {
		return *x.IrodsPamTtl
	}
	return 0
}

func (x *Account) GetIrodsSslServerName() string {
	if x != nil && x.IrodsSslServerName != nil {
		return *x.IrodsSslServerName
	}
	return ""
}

type PathMapping struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IrodsPath           string                 `protobuf:"bytes,1,opt,name=irods_path,json=irodsPath,proto3" json:"irods_path,omitempty"`
	MappingPath         string                 `protobuf:"bytes,2,opt,name=mapping_path,json=mappingPath,proto3" json:"mapping_path,omitempty"`
	ResourceType        string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ReadOnly            bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	CreateDir           bool                   `protobuf:"varint,5,opt,name=create_dir,json=createDir,proto3" json:"create_dir,omitempty"`
	IgnoreNotExistError bool                   `protobuf:"varint,6,opt,name=ignore_not_exist_error,json=ignoreNotExistError,proto3" json:"ignore_not_exist_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PathMapping) Reset() {
	*x = PathMapping{}
	mi := &file_service_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMapping) ProtoMessage() {}

func (x *PathMapping) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMapping.ProtoReflect.Descriptor instead.
func (*PathMapping) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *PathMapping) GetIrodsPath() string {
	if x != nil {
		return x.IrodsPath
	}
	return ""
}

func (x *PathMapping) GetMappingPath() string {
	if x != nil {
		return x.MappingPath
	}
	return ""
}

func (x *PathMapping) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PathMapping) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *PathMapping) GetCreateDir() bool {
	if x != nil {
		return x.CreateDir
	}
	return false
}

func (x *PathMapping) GetIgnoreNotExistError() bool {
	if x != nil {
		return x.IgnoreNotExistError
	}
	return false
}

type ConnectionConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreationTimeout      *durationpb.Duration   `protobuf:"bytes,1,opt,name=creation_timeout,json=creationTimeout,proto3,oneof" json:"creation_timeout,omitempty"`
	InitNumber           *int32                 `protobuf:"varint,2,opt,name=init_number,json=initNumber,proto3,oneof" json:"init_number,omitempty"`
	MaxNumber            *int32                 `protobuf:"varint,3,opt,name=max_number,json=maxNumber,proto3,oneof" json:"max_number,omitempty"`
	MaxIdleNumber        *int32                 `protobuf:"varint,4,opt,name=max_idle_number,json=maxIdleNumber,proto3,oneof" json:"max_idle_number,omitempty"`
	Lifespan             *durationpb.Duration   `protobuf:"bytes,5,opt,name=lifespan,proto3,oneof" json:"lifespan,omitempty"`
	IdleTimeout          *durationpb.Duration   `protobuf:"bytes,6,opt,name=idle_timeout,json=idleTimeout,proto3,oneof" json:"idle_timeout,omitempty"`
	OperationTimeout     *durationpb.Duration   `protobuf:"bytes,7,opt,name=operation_timeout,json=operationTimeout,proto3,oneof" json:"operation_timeout,omitempty"`
	LongOperationTimeout *durationpb.Duration   `protobuf:"bytes,8,opt,name=long_operation_timeout,json=longOperationTimeout,proto3,oneof" json:"long_operation_timeout,omitempty"`
	TcpBufferSize        *int32                 `protobuf:"varint,9,opt,name=tcp_buffer_size,json=tcpBufferSize,proto3,oneof" json:"tcp_buffer_size,omitempty"`
	WaitConnection       *bool                  `protobuf:"varint,10,opt,name=wait_connection,json=waitConnection,proto3,oneof" json:"wait_connection,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectionConfig) Reset() {
	*x = ConnectionConfig{}
	mi := &file_service_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionConfig) ProtoMessage() {}

func (x *ConnectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionConfig.ProtoReflect.Descriptor instead.
func (*ConnectionConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionConfig) GetCreationTimeout() *durationpb.Duration {
	if x != nil {
		return x.CreationTimeout
	}
	return nil
}

func (x *ConnectionConfig) GetInitNumber() int32 {
	if x != nil && x.InitNumber != nil {
		return *x.InitNumber
	}
	return 0
}

func (x *ConnectionConfig) GetMaxNumber() int32 {
	if x != nil && x.MaxNumber != nil {
		return *x.MaxNumber
	}
	return 0
}

func (x *ConnectionConfig) GetMaxIdleNumber() int32 {
	if x != nil && x.MaxIdleNumber != nil {
		return *x.MaxIdleNumber
	}
	return 0
}

func (x *ConnectionConfig) GetLifespan() *durationpb.Duration {
	if x != nil {
		return x.Lifespan
	}
	return nil
}

func (x *ConnectionConfig) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

func (x *ConnectionConfig) GetOperationTimeout() *durationpb.Duration {
	if x != nil {
		return x.OperationTimeout
	}
	return nil
}

func (x *ConnectionConfig) GetLongOperationTimeout() *durationpb.Duration {
	if x != nil {
		return x.LongOperationTimeout
	}
	return nil
}

func (x *ConnectionConfig) GetTcpBufferSize() int32 {
	if x != nil && x.TcpBufferSize != nil {
		return *x.TcpBufferSize
	}
	return 0
}

func (x *ConnectionConfig) GetWaitConnection() bool {
	if x != nil && x.WaitConnection != nil {
		return *x.WaitConnection
	}
	return false
}

type MetadataCacheTimeoutSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Inherit       *bool                  `protobuf:"varint,3,opt,name=inherit,proto3,oneof" json:"inherit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataCacheTimeoutSetting) Reset() {
	*x = MetadataCacheTimeoutSetting{}
	mi := &file_service_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataCacheTimeoutSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataCacheTimeoutSetting) ProtoMessage() {}

func (x *MetadataCacheTimeoutSetting) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataCacheTimeoutSetting.ProtoReflect.Descriptor instead.
func (*MetadataCacheTimeoutSetting) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataCacheTimeoutSetting) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MetadataCacheTimeoutSetting) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *MetadataCacheTimeoutSetting) GetInherit() bool {
	if x != nil && x.Inherit != nil {
		return *x.Inherit
	}
	return false
}

type MemoryBackendConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CleanupInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=cleanup_interval,json=cleanupInterval,proto3,oneof" json:"cleanup_interval,omitempty"`
	DefaultTtl      *durationpb.Duration   `protobuf:"bytes,2,opt,name=default_ttl,json=defaultTtl,proto3,oneof" json:"default_ttl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryBackendConfig) Reset() {
	*x = MemoryBackendConfig{}
	mi := &file_service_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryBackendConfig) ProtoMessage() {}

func (x *MemoryBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryBackendConfig.ProtoReflect.Descriptor instead.
func (*MemoryBackendConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryBackendConfig) GetCleanupInterval() *durationpb.Duration {
	if x != nil {
		return x.CleanupInterval
	}
	return nil
}

func (x *MemoryBackendConfig) GetDefaultTtl() *durationpb.Duration {
	if x != nil {
		return x.DefaultTtl
	}
	return nil
}

type RistrettoBackendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxEntries    *int64                 `protobuf:"varint,1,opt,name=max_entries,json=maxEntries,proto3,oneof" json:"max_entries,omitempty"`
	MaxCost       *int64                 `protobuf:"varint,2,opt,name=max_cost,json=maxCost,proto3,oneof" json:"max_cost,omitempty"`
	BufferItems   *int64                 `protobuf:"varint,3,opt,name=buffer_items,json=bufferItems,proto3,oneof" json:"buffer_items,omitempty"`
	DefaultTtl    *durationpb.Duration   `protobuf:"bytes,4,opt,name=default_ttl,json=defaultTtl,proto3,oneof" json:"default_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RistrettoBackendConfig) Reset() {
	*x = RistrettoBackendConfig{}
	mi := &file_service_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RistrettoBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RistrettoBackendConfig) ProtoMessage() {}

func (x *RistrettoBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RistrettoBackendConfig.ProtoReflect.Descriptor instead.
func (*RistrettoBackendConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *RistrettoBackendConfig) GetMaxEntries() int64 {
	if x != nil && x.MaxEntries != nil {
		return *x.MaxEntries
	}
	return 0
}

func (x *RistrettoBackendConfig) GetMaxCost() int64 {
	if x != nil && x.MaxCost != nil {
		return *x.MaxCost
	}
	return 0
}

func (x *RistrettoBackendConfig) GetBufferItems() int64 {
	if x != nil && x.BufferItems != nil {
		return *x.BufferItems
	}
	return 0
}

func (x *RistrettoBackendConfig) GetDefaultTtl() *durationpb.Duration {
	if x != nil {
		return x.DefaultTtl
	}
	return nil
}

type RedisBackendConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Address                *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Db                     *int32                 `protobuf:"varint,2,opt,name=db,proto3,oneof" json:"db,omitempty"`
	Password               *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	PoolSize               *int32                 `protobuf:"varint,4,opt,name=pool_size,json=poolSize,proto3,oneof" json:"pool_size,omitempty"`
	KeyPrefix              *string                `protobuf:"bytes,5,opt,name=key_prefix,json=keyPrefix,proto3,oneof" json:"key_prefix,omitempty"`
	ConnectTimeout         *durationpb.Duration   `protobuf:"bytes,6,opt,name=connect_timeout,json=connectTimeout,proto3,oneof" json:"connect_timeout,omitempty"`
	CommandTimeout         *durationpb.Duration   `protobuf:"bytes,7,opt,name=command_timeout,json=commandTimeout,proto3,oneof" json:"command_timeout,omitempty"`
	DefaultTtl             *durationpb.Duration   `protobuf:"bytes,8,opt,name=default_ttl,json=defaultTtl,proto3,oneof" json:"default_ttl,omitempty"`
	EnableAccountIsolation *bool                  `protobuf:"varint,9,opt,name=enable_account_isolation,json=enableAccountIsolation,proto3,oneof" json:"enable_account_isolation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RedisBackendConfig) Reset() {
	*x = RedisBackendConfig{}
	mi := &file_service_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisBackendConfig) ProtoMessage() {}

func (x *RedisBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisBackendConfig.ProtoReflect.Descriptor instead.
func (*RedisBackendConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *RedisBackendConfig) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *RedisBackendConfig) GetDb() int32 {
	if x != nil && x.Db != nil {
		return *x.Db
	}
	return 0
}

func (x *RedisBackendConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RedisBackendConfig) GetPoolSize() int32 {
	if x != nil && x.PoolSize != nil {
		return *x.PoolSize
	}
	return 0
}

func (x *RedisBackendConfig) GetKeyPrefix() string {
	if x != nil && x.KeyPrefix != nil {
		return *x.KeyPrefix
	}
	return ""
}

func (x *RedisBackendConfig) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

func (x *RedisBackendConfig) GetCommandTimeout() *durationpb.Duration {
	if x != nil {
		return x.CommandTimeout
	}
	return nil
}

func (x *RedisBackendConfig) GetDefaultTtl() *durationpb.Duration {
	if x != nil {
		return x.DefaultTtl
	}
	return nil
}

func (x *RedisBackendConfig) GetEnableAccountIsolation() bool {
	if x != nil && x.EnableAccountIsolation != nil {
		return *x.EnableAccountIsolation
	}
	return false
}

type CacheBackendConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          string                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Memory        *MemoryBackendConfig    `protobuf:"bytes,2,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	Ristretto     *RistrettoBackendConfig `protobuf:"bytes,3,opt,name=ristretto,proto3,oneof" json:"ristretto,omitempty"`
	Redis         *RedisBackendConfig     `protobuf:"bytes,4,opt,name=redis,proto3,oneof" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheBackendConfig) Reset() {
	*x = CacheBackendConfig{}
	mi := &file_service_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBackendConfig) ProtoMessage() {}

func (x *CacheBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBackendConfig.ProtoReflect.Descriptor instead.
func (*CacheBackendConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *CacheBackendConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CacheBackendConfig) GetMemory() *MemoryBackendConfig {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *CacheBackendConfig) GetRistretto() *RistrettoBackendConfig {
	if x != nil {
		return x.Ristretto
	}
	return nil
}

func (x *CacheBackendConfig) GetRedis() *RedisBackendConfig {
	if x != nil {
		return x.Redis
	}
	return nil
}

type CacheConfig struct {
	state                   protoimpl.MessageState         `protogen:"open.v1"`
	MetadataTimeoutSettings []*MetadataCacheTimeoutSetting `protobuf:"bytes,1,rep,name=metadata_timeout_settings,json=metadataTimeoutSettings,proto3" json:"metadata_timeout_settings,omitempty"`
	StartNewTransaction     *bool                          `protobuf:"varint,2,opt,name=start_new_transaction,json=startNewTransaction,proto3,oneof" json:"start_new_transaction,omitempty"`
	Backend                 *CacheBackendConfig            `protobuf:"bytes,3,opt,name=backend,proto3,oneof" json:"backend,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CacheConfig) Reset() {
	*x = CacheConfig{}
	mi := &file_service_api_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfig) ProtoMessage() {}

func (x *CacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfig.ProtoReflect.Descriptor instead.
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *CacheConfig) GetMetadataTimeoutSettings() []*MetadataCacheTimeoutSetting {
	if x != nil {
		return x.MetadataTimeoutSettings
	}
	return nil
}

func (x *CacheConfig) GetStartNewTransaction() bool {
	if x != nil && x.StartNewTransaction != nil {
		return *x.StartNewTransaction
	}
	return false
}

func (x *CacheConfig) GetBackend() *CacheBackendConfig {
	if x != nil {
		return x.Backend
	}
	return nil
}

// IRODSFSConfig contains settings passed to the irodsfs client.
type IRODSFSConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Account            *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PathMappings       []*PathMapping         `protobuf:"bytes,2,rep,name=path_mappings,json=pathMappings,proto3" json:"path_mappings,omitempty"`
	ReadAheadMax       *int32                 `protobuf:"varint,3,opt,name=read_ahead_max,json=readAheadMax,proto3,oneof" json:"read_ahead_max,omitempty"`
	ReadWriteMax       *int32                 `protobuf:"varint,4,opt,name=read_write_max,json=readWriteMax,proto3,oneof" json:"read_write_max,omitempty"`
	FuseOptions        []string               `protobuf:"bytes,5,rep,name=fuse_options,json=fuseOptions,proto3" json:"fuse_options,omitempty"`
	Uid                *int32                 `protobuf:"varint,6,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	Gid                *int32                 `protobuf:"varint,7,opt,name=gid,proto3,oneof" json:"gid,omitempty"`
	SystemUser         *string                `protobuf:"bytes,8,opt,name=system_user,json=systemUser,proto3,oneof" json:"system_user,omitempty"`
	MetadataConnection *ConnectionConfig      `protobuf:"bytes,9,opt,name=metadata_connection,json=metadataConnection,proto3,oneof" json:"metadata_connection,omitempty"`
	IoConnection       *ConnectionConfig      `protobuf:"bytes,10,opt,name=io_connection,json=ioConnection,proto3,oneof" json:"io_connection,omitempty"`
	Cache              *CacheConfig           `protobuf:"bytes,11,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	PoolEndpoint       *string                `protobuf:"bytes,12,opt,name=pool_endpoint,json=poolEndpoint,proto3,oneof" json:"pool_endpoint,omitempty"`
	Debug              bool                   `protobuf:"varint,13,opt,name=debug,proto3" json:"debug,omitempty"`
	Description        *string                `protobuf:"bytes,14,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IRODSFSConfig) Reset() {
	*x = IRODSFSConfig{}
	mi := &file_service_api_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IRODSFSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRODSFSConfig) ProtoMessage() {}

func (x *IRODSFSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRODSFSConfig.ProtoReflect.Descriptor instead.
func (*IRODSFSConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *IRODSFSConfig) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *IRODSFSConfig) GetPathMappings() []*PathMapping {
	if x != nil {
		return x.PathMappings
	}
	return nil
}

func (x *IRODSFSConfig) GetReadAheadMax() int32 {
	if x != nil && x.ReadAheadMax != nil {
		return *x.ReadAheadMax
	}
	return 0
}

func (x *IRODSFSConfig) GetReadWriteMax() int32 {
	if x != nil && x.ReadWriteMax != nil {
		return *x.ReadWriteMax
	}
	return 0
}

func (x *IRODSFSConfig) GetFuseOptions() []string {
	if x != nil {
		return x.FuseOptions
	}
	return nil
}

func (x *IRODSFSConfig) GetUid() int32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *IRODSFSConfig) GetGid() int32 {
	if x != nil && x.Gid != nil {
		return *x.Gid
	}
	return 0
}

func (x *IRODSFSConfig) GetSystemUser() string {
	if x != nil && x.SystemUser != nil {
		return *x.SystemUser
	}
	return ""
}

func (x *IRODSFSConfig) GetMetadataConnection() *ConnectionConfig {
	if x != nil {
		return x.MetadataConnection
	}
	return nil
}

func (x *IRODSFSConfig) GetIoConnection() *ConnectionConfig {
	if x != nil {
		return x.IoConnection
	}
	return nil
}

func (x *IRODSFSConfig) GetCache() *CacheConfig {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *IRODSFSConfig) GetPoolEndpoint() string {
	if x != nil && x.PoolEndpoint != nil {
		return *x.PoolEndpoint
	}
	return ""
}

func (x *IRODSFSConfig) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *IRODSFSConfig) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DAVFSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAVFSConfig) Reset() {
	*x = DAVFSConfig{}
	mi := &file_service_api_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAVFSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAVFSConfig) ProtoMessage() {}

func (x *DAVFSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAVFSConfig.ProtoReflect.Descriptor instead.
func (*DAVFSConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *DAVFSConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DAVFSConfig) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *DAVFSConfig) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *DAVFSConfig) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type NFSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFSConfig) Reset() {
	*x = NFSConfig{}
	mi := &file_service_api_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFSConfig) ProtoMessage() {}

func (x *NFSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFSConfig.ProtoReflect.Descriptor instead.
func (*NFSConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *NFSConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NFSConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NFSConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// MountConfig contains settings shared by all mount clients and exactly one
// client-specific configuration.
type MountConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MountPath    string                 `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly     bool                   `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	MountOptions []string               `protobuf:"bytes,3,rep,name=mount_options,json=mountOptions,proto3" json:"mount_options,omitempty"`
	// Types that are valid to be assigned to ClientConfig:
	//
	//	*MountConfig_Irodsfs
	//	*MountConfig_Davfs
	//	*MountConfig_Nfs
	ClientConfig  isMountConfig_ClientConfig `protobuf_oneof:"client_config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountConfig) Reset() {
	*x = MountConfig{}
	mi := &file_service_api_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountConfig) ProtoMessage() {}

func (x *MountConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountConfig.ProtoReflect.Descriptor instead.
func (*MountConfig) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *MountConfig) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *MountConfig) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MountConfig) GetMountOptions() []string {
	if x != nil {
		return x.MountOptions
	}
	return nil
}

func (x *MountConfig) GetClientConfig() isMountConfig_ClientConfig {
	if x != nil {
		return x.ClientConfig
	}
	return nil
}

func (x *MountConfig) GetIrodsfs() *IRODSFSConfig {
	if x != nil {
		if x, ok := x.ClientConfig.(*MountConfig_Irodsfs); ok {
			return x.Irodsfs
		}
	}
	return nil
}

func (x *MountConfig) GetDavfs() *DAVFSConfig {
	if x != nil {
		if x, ok := x.ClientConfig.(*MountConfig_Davfs); ok {
			return x.Davfs
		}
	}
	return nil
}

func (x *MountConfig) GetNfs() *NFSConfig {
	if x != nil {
		if x, ok := x.ClientConfig.(*MountConfig_Nfs); ok {
			return x.Nfs
		}
	}
	return nil
}

type isMountConfig_ClientConfig interface {
	isMountConfig_ClientConfig()
}

type MountConfig_Irodsfs struct {
	Irodsfs *IRODSFSConfig `protobuf:"bytes,10,opt,name=irodsfs,proto3,oneof"`
}

type MountConfig_Davfs struct {
	Davfs *DAVFSConfig `protobuf:"bytes,11,opt,name=davfs,proto3,oneof"`
}

type MountConfig_Nfs struct {
	Nfs *NFSConfig `protobuf:"bytes,12,opt,name=nfs,proto3,oneof"`
}

func (*MountConfig_Irodsfs) isMountConfig_ClientConfig() {}

func (*MountConfig_Davfs) isMountConfig_ClientConfig() {}

func (*MountConfig_Nfs) isMountConfig_ClientConfig() {}

type APIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIError) Reset() {
	*x = APIError{}
	mi := &file_service_api_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *APIError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *APIError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// MountInfo reuses the submitted MountConfig. iRODS credentials, Redis backend
// password, and DAVFS password are redacted and never contain original values.
type MountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	State         MountState             `protobuf:"varint,2,opt,name=state,proto3,enum=api.MountState" json:"state,omitempty"`
	Config        *MountConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError     *APIError              `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Pid           int64                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MountedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=mounted_at,json=mountedAt,proto3" json:"mounted_at,omitempty"`
	UnmountedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=unmounted_at,json=unmountedAt,proto3" json:"unmounted_at,omitempty"`
	NextRetryAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountInfo) Reset() {
	*x = MountInfo{}
	mi := &file_service_api_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountInfo) ProtoMessage() {}

func (x *MountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountInfo.ProtoReflect.Descriptor instead.
func (*MountInfo) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *MountInfo) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *MountInfo) GetState() MountState {
	if x != nil {
		return x.State
	}
	return MountState_MOUNT_STATE_UNSPECIFIED
}

func (x *MountInfo) GetConfig() *MountConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MountInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MountInfo) GetLastError() *APIError {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *MountInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MountInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MountInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MountInfo) GetMountedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MountedAt
	}
	return nil
}

func (x *MountInfo) GetUnmountedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnmountedAt
	}
	return nil
}

func (x *MountInfo) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

type MountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If omitted, the server generates a mount ID. A supplied ID must be unique.
	MountId       *string      `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3,oneof" json:"mount_id,omitempty"`
	Config        *MountConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_service_api_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *MountRequest) GetMountId() string {
	if x != nil && x.MountId != nil {
		return *x.MountId
	}
	return ""
}

func (x *MountRequest) GetConfig() *MountConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         *MountInfo             `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_service_api_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *MountResponse) GetMount() *MountInfo {
	if x != nil {
		return x.Mount
	}
	return nil
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_service_api_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *UnmountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type UnmountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record remains queryable in an unmounting state until cleanup finishes.
	Mount         *MountInfo `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	mi := &file_service_api_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *UnmountResponse) GetMount() *MountInfo {
	if x != nil {
		return x.Mount
	}
	return nil
}

type ListMountsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	States          []MountState           `protobuf:"varint,1,rep,packed,name=states,proto3,enum=api.MountState" json:"states,omitempty"`
	MountPathPrefix *string                `protobuf:"bytes,2,opt,name=mount_path_prefix,json=mountPathPrefix,proto3,oneof" json:"mount_path_prefix,omitempty"`
	ClientUser      *string                `protobuf:"bytes,3,opt,name=client_user,json=clientUser,proto3,oneof" json:"client_user,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMountsRequest) Reset() {
	*x = ListMountsRequest{}
	mi := &file_service_api_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsRequest) ProtoMessage() {}

func (x *ListMountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsRequest.ProtoReflect.Descriptor instead.
func (*ListMountsRequest) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{19}
}

func (x *ListMountsRequest) GetStates() []MountState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListMountsRequest) GetMountPathPrefix() string {
	if x != nil && x.MountPathPrefix != nil {
		return *x.MountPathPrefix
	}
	return ""
}

func (x *ListMountsRequest) GetClientUser() string {
	if x != nil && x.ClientUser != nil {
		return *x.ClientUser
	}
	return ""
}

type ListMountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*MountInfo           `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMountsResponse) Reset() {
	*x = ListMountsResponse{}
	mi := &file_service_api_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMountsResponse) ProtoMessage() {}

func (x *ListMountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMountsResponse.ProtoReflect.Descriptor instead.
func (*ListMountsResponse) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListMountsResponse) GetMounts() []*MountInfo {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type GetMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       string                 `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountRequest) Reset() {
	*x = GetMountRequest{}
	mi := &file_service_api_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountRequest) ProtoMessage() {}

func (x *GetMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountRequest.ProtoReflect.Descriptor instead.
func (*GetMountRequest) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{21}
}

func (x *GetMountRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type GetMountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         *MountInfo             `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMountResponse) Reset() {
	*x = GetMountResponse{}
	mi := &file_service_api_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMountResponse) ProtoMessage() {}

func (x *GetMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMountResponse.ProtoReflect.Descriptor instead.
func (*GetMountResponse) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetMountResponse) GetMount() *MountInfo {
	if x != nil {
		return x.Mount
	}
	return nil
}

// WatchMountEventsRequest filters lifecycle events. Empty mount_ids selects
// every mount; include_current first emits the currently known snapshots.
type WatchMountEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MountIds       []string               `protobuf:"bytes,1,rep,name=mount_ids,json=mountIds,proto3" json:"mount_ids,omitempty"`
	IncludeCurrent bool                   `protobuf:"varint,2,opt,name=include_current,json=includeCurrent,proto3" json:"include_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchMountEventsRequest) Reset() {
	*x = WatchMountEventsRequest{}
	mi := &file_service_api_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMountEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMountEventsRequest) ProtoMessage() {}

func (x *WatchMountEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMountEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchMountEventsRequest) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{23}
}

func (x *WatchMountEventsRequest) GetMountIds() []string {
	if x != nil {
		return x.MountIds
	}
	return nil
}

func (x *WatchMountEventsRequest) GetIncludeCurrent() bool {
	if x != nil {
		return x.IncludeCurrent
	}
	return false
}

// MountEvent always contains a redacted MountInfo. REMOVED is the final
// snapshot emitted after an unmount record has been deleted.
type MountEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MountEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=api.MountEventType" json:"type,omitempty"`
	Mount         *MountInfo             `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountEvent) Reset() {
	*x = MountEvent{}
	mi := &file_service_api_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountEvent) ProtoMessage() {}

func (x *MountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_api_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountEvent.ProtoReflect.Descriptor instead.
func (*MountEvent) Descriptor() ([]byte, []int) {
	return file_service_api_api_proto_rawDescGZIP(), []int{24}
}

func (x *MountEvent) GetType() MountEventType {
	if x != nil {
		return x.Type
	}
	return MountEventType_MOUNT_EVENT_TYPE_UNSPECIFIED
}

func (x *MountEvent) GetMount() *MountInfo {
	if x != nil {
		return x.Mount
	}
	return nil
}

var File_service_api_api_proto protoreflect.FileDescriptor

const file_service_api_api_proto_rawDesc = "" +
	"\n" +
	"\x15service/api/api.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xaf\x12\n" +
	"\aAccount\x12C\n" +
	"\x1birods_authentication_scheme\x18\x01 \x01(\tH\x00R\x19irodsAuthenticationScheme\x88\x01\x01\x12J\n" +
	"\x1firods_client_server_negotiation\x18\x02 \x01(\bH\x01R\x1cirodsClientServerNegotiation\x88\x01\x01\x12@\n" +
	"\x1airods_client_server_policy\x18\x03 \x01(\tH\x02R\x17irodsClientServerPolicy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"irods_host\x18\x04 \x01(\tR\tirodsHost\x12\x1d\n" +
	"\n" +
	"irods_port\x18\x05 \x01(\x05R\tirodsPort\x12&\n" +
	"\x0firods_zone_name\x18\x06 \x01(\tR\rirodsZoneName\x128\n" +
	"\x16irods_client_zone_name\x18\a \x01(\tH\x03R\x13irodsClientZoneName\x88\x01\x01\x12&\n" +
	"\x0firods_user_name\x18\b \x01(\tR\rirodsUserName\x128\n" +
	"\x16irods_client_user_name\x18\t \x01(\tH\x04R\x13irodsClientUserName\x88\x01\x01\x129\n" +
	"\x16irods_default_resource\x18\n" +
	" \x01(\tH\x05R\x14irodsDefaultResource\x88\x01\x01\x12 \n" +
	"\tirods_cwd\x18\v \x01(\tH\x06R\birodsCwd\x88\x01\x01\x12\"\n" +
	"\n" +
	"irods_home\x18\f \x01(\tH\aR\tirodsHome\x88\x01\x01\x12>\n" +
	"\x19irods_default_hash_scheme\x18\r \x01(\tH\bR\x16irodsDefaultHashScheme\x88\x01\x01\x12:\n" +
	"\x17irods_match_hash_policy\x18\x0e \x01(\tH\tR\x14irodsMatchHashPolicy\x88\x01\x01\x12A\n" +
	"\x1airods_encryption_algorithm\x18\x0f \x01(\tH\n" +
	"R\x18irodsEncryptionAlgorithm\x88\x01\x01\x12>\n" +
	"\x19irods_encryption_key_size\x18\x10 \x01(\x05H\vR\x16irodsEncryptionKeySize\x88\x01\x01\x12@\n" +
	"\x1airods_encryption_salt_size\x18\x11 \x01(\x05H\fR\x17irodsEncryptionSaltSize\x88\x01\x01\x12K\n" +
	" irods_encryption_num_hash_rounds\x18\x12 \x01(\x05H\rR\x1cirodsEncryptionNumHashRounds\x88\x01\x01\x12E\n" +
	"\x1dirods_ssl_ca_certificate_file\x18\x13 \x01(\tH\x0eR\x19irodsSslCaCertificateFile\x88\x01\x01\x12E\n" +
	"\x1dirods_ssl_ca_certificate_path\x18\x14 \x01(\tH\x0fR\x19irodsSslCaCertificatePath\x88\x01\x01\x12:\n" +
	"\x17irods_ssl_verify_server\x18\x15 \x01(\tH\x10R\x14irodsSslVerifyServer\x88\x01\x01\x12K\n" +
	" irods_ssl_certificate_chain_file\x18\x16 \x01(\tH\x11R\x1cirodsSslCertificateChainFile\x88\x01\x01\x12G\n" +
	"\x1eirods_ssl_certificate_key_file\x18\x17 \x01(\tH\x12R\x1airodsSslCertificateKeyFile\x88\x01\x01\x12;\n" +
	"\x18irods_ssl_dh_params_file\x18\x18 \x01(\tH\x13R\x14irodsSslDhParamsFile\x88\x01\x01\x123\n" +
	"\x13irods_user_password\x18\x19 \x01(\tH\x14R\x11irodsUserPassword\x88\x01\x01\x12&\n" +
	"\firods_ticket\x18\x1a \x01(\tH\x15R\virodsTicket\x88\x01\x01\x12+\n" +
	"\x0firods_pam_token\x18\x1b \x01(\tH\x16R\rirodsPamToken\x88\x01\x01\x12'\n" +
	"\rirods_pam_ttl\x18\x1c \x01(\x05H\x17R\virodsPamTtl\x88\x01\x01\x126\n" +
	"\x15irods_ssl_server_name\x18\x1d \x01(\tH\x18R\x12irodsSslServerName\x88\x01\x01B\x1e\n" +
	"\x1c_irods_authentication_schemeB\"\n" +
	" _irods_client_server_negotiationB\x1d\n" +
	"\x1b_irods_client_server_policyB\x19\n" +
	"\x17_irods_client_zone_nameB\x19\n" +
	"\x17_irods_client_user_nameB\x19\n" +
	"\x17_irods_default_resourceB\f\n" +
	"\n" +
	"_irods_cwdB\r\n" +
	"\v_irods_homeB\x1c\n" +
	"\x1a_irods_default_hash_schemeB\x1a\n" +
	"\x18_irods_match_hash_policyB\x1d\n" +
	"\x1b_irods_encryption_algorithmB\x1c\n" +
	"\x1a_irods_encryption_key_sizeB\x1d\n" +
	"\x1b_irods_encryption_salt_sizeB#\n" +
	"!_irods_encryption_num_hash_roundsB \n" +
	"\x1e_irods_ssl_ca_certificate_fileB \n" +
	"\x1e_irods_ssl_ca_certificate_pathB\x1a\n" +
	"\x18_irods_ssl_verify_serverB#\n" +
	"!_irods_ssl_certificate_chain_fileB!\n" +
	"\x1f_irods_ssl_certificate_key_fileB\x1b\n" +
	"\x19_irods_ssl_dh_params_fileB\x16\n" +
	"\x14_irods_user_passwordB\x0f\n" +
	"\r_irods_ticketB\x12\n" +
	"\x10_irods_pam_tokenB\x10\n" +
	"\x0e_irods_pam_ttlB\x18\n" +
	"\x16_irods_ssl_server_name\"\xe5\x01\n" +
	"\vPathMapping\x12\x1d\n" +
	"\n" +
	"irods_path\x18\x01 \x01(\tR\tirodsPath\x12!\n" +
	"\fmapping_path\x18\x02 \x01(\tR\vmappingPath\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"create_dir\x18\x05 \x01(\bR\tcreateDir\x123\n" +
	"\x16ignore_not_exist_error\x18\x06 \x01(\bR\x13ignoreNotExistError\"\x90\x06\n" +
	"\x10ConnectionConfig\x12I\n" +
	"\x10creation_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x0fcreationTimeout\x88\x01\x01\x12$\n" +
	"\vinit_number\x18\x02 \x01(\x05H\x01R\n" +
	"initNumber\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_number\x18\x03 \x01(\x05H\x02R\tmaxNumber\x88\x01\x01\x12+\n" +
	"\x0fmax_idle_number\x18\x04 \x01(\x05H\x03R\rmaxIdleNumber\x88\x01\x01\x12:\n" +
	"\blifespan\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x04R\blifespan\x88\x01\x01\x12A\n" +
	"\fidle_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x05R\vidleTimeout\x88\x01\x01\x12K\n" +
	"\x11operation_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationH\x06R\x10operationTimeout\x88\x01\x01\x12T\n" +
	"\x16long_operation_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationH\aR\x14longOperationTimeout\x88\x01\x01\x12+\n" +
	"\x0ftcp_buffer_size\x18\t \x01(\x05H\bR\rtcpBufferSize\x88\x01\x01\x12,\n" +
	"\x0fwait_connection\x18\n" +
	" \x01(\bH\tR\x0ewaitConnection\x88\x01\x01B\x13\n" +
	"\x11_creation_timeoutB\x0e\n" +
	"\f_init_numberB\r\n" +
	"\v_max_numberB\x12\n" +
	"\x10_max_idle_numberB\v\n" +
	"\t_lifespanB\x0f\n" +
	"\r_idle_timeoutB\x14\n" +
	"\x12_operation_timeoutB\x19\n" +
	"\x17_long_operation_timeoutB\x12\n" +
	"\x10_tcp_buffer_sizeB\x12\n" +
	"\x10_wait_connection\"\x91\x01\n" +
	"\x1bMetadataCacheTimeoutSetting\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\ainherit\x18\x03 \x01(\bH\x00R\ainherit\x88\x01\x01B\n" +
	"\n" +
	"\b_inherit\"\xc6\x01\n" +
	"\x13MemoryBackendConfig\x12I\n" +
	"\x10cleanup_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x0fcleanupInterval\x88\x01\x01\x12?\n" +
	"\vdefault_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\n" +
	"defaultTtl\x88\x01\x01B\x13\n" +
	"\x11_cleanup_intervalB\x0e\n" +
	"\f_default_ttl\"\x85\x02\n" +
	"\x16RistrettoBackendConfig\x12$\n" +
	"\vmax_entries\x18\x01 \x01(\x03H\x00R\n" +
	"maxEntries\x88\x01\x01\x12\x1e\n" +
	"\bmax_cost\x18\x02 \x01(\x03H\x01R\amaxCost\x88\x01\x01\x12&\n" +
	"\fbuffer_items\x18\x03 \x01(\x03H\x02R\vbufferItems\x88\x01\x01\x12?\n" +
	"\vdefault_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x03R\n" +
	"defaultTtl\x88\x01\x01B\x0e\n" +
	"\f_max_entriesB\v\n" +
	"\t_max_costB\x0f\n" +
	"\r_buffer_itemsB\x0e\n" +
	"\f_default_ttl\"\xd3\x04\n" +
	"\x12RedisBackendConfig\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x13\n" +
	"\x02db\x18\x02 \x01(\x05H\x01R\x02db\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x02R\bpassword\x88\x01\x01\x12 \n" +
	"\tpool_size\x18\x04 \x01(\x05H\x03R\bpoolSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"key_prefix\x18\x05 \x01(\tH\x04R\tkeyPrefix\x88\x01\x01\x12G\n" +
	"\x0fconnect_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x05R\x0econnectTimeout\x88\x01\x01\x12G\n" +
	"\x0fcommand_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationH\x06R\x0ecommandTimeout\x88\x01\x01\x12?\n" +
	"\vdefault_ttl\x18\b \x01(\v2\x19.google.protobuf.DurationH\aR\n" +
	"defaultTtl\x88\x01\x01\x12=\n" +
	"\x18enable_account_isolation\x18\t \x01(\bH\bR\x16enableAccountIsolation\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\x05\n" +
	"\x03_dbB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_pool_sizeB\r\n" +
	"\v_key_prefixB\x12\n" +
	"\x10_connect_timeoutB\x12\n" +
	"\x10_command_timeoutB\x0e\n" +
	"\f_default_ttlB\x1b\n" +
	"\x19_enable_account_isolation\"\xf6\x01\n" +
	"\x12CacheBackendConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\x06memory\x18\x02 \x01(\v2\x18.api.MemoryBackendConfigH\x00R\x06memory\x88\x01\x01\x12>\n" +
	"\tristretto\x18\x03 \x01(\v2\x1b.api.RistrettoBackendConfigH\x01R\tristretto\x88\x01\x01\x122\n" +
	"\x05redis\x18\x04 \x01(\v2\x17.api.RedisBackendConfigH\x02R\x05redis\x88\x01\x01B\t\n" +
	"\a_memoryB\f\n" +
	"\n" +
	"_ristrettoB\b\n" +
	"\x06_redis\"\x82\x02\n" +
	"\vCacheConfig\x12\\\n" +
	"\x19metadata_timeout_settings\x18\x01 \x03(\v2 .api.MetadataCacheTimeoutSettingR\x17metadataTimeoutSettings\x127\n" +
	"\x15start_new_transaction\x18\x02 \x01(\bH\x00R\x13startNewTransaction\x88\x01\x01\x126\n" +
	"\abackend\x18\x03 \x01(\v2\x17.api.CacheBackendConfigH\x01R\abackend\x88\x01\x01B\x18\n" +
	"\x16_start_new_transactionB\n" +
	"\n" +
	"\b_backend\"\xf9\x05\n" +
	"\rIRODSFSConfig\x12&\n" +
	"\aaccount\x18\x01 \x01(\v2\f.api.AccountR\aaccount\x125\n" +
	"\rpath_mappings\x18\x02 \x03(\v2\x10.api.PathMappingR\fpathMappings\x12)\n" +
	"\x0eread_ahead_max\x18\x03 \x01(\x05H\x00R\freadAheadMax\x88\x01\x01\x12)\n" +
	"\x0eread_write_max\x18\x04 \x01(\x05H\x01R\freadWriteMax\x88\x01\x01\x12!\n" +
	"\ffuse_options\x18\x05 \x03(\tR\vfuseOptions\x12\x15\n" +
	"\x03uid\x18\x06 \x01(\x05H\x02R\x03uid\x88\x01\x01\x12\x15\n" +
	"\x03gid\x18\a \x01(\x05H\x03R\x03gid\x88\x01\x01\x12$\n" +
	"\vsystem_user\x18\b \x01(\tH\x04R\n" +
	"systemUser\x88\x01\x01\x12K\n" +
	"\x13metadata_connection\x18\t \x01(\v2\x15.api.ConnectionConfigH\x05R\x12metadataConnection\x88\x01\x01\x12?\n" +
	"\rio_connection\x18\n" +
	" \x01(\v2\x15.api.ConnectionConfigH\x06R\fioConnection\x88\x01\x01\x12+\n" +
	"\x05cache\x18\v \x01(\v2\x10.api.CacheConfigH\aR\x05cache\x88\x01\x01\x12(\n" +
	"\rpool_endpoint\x18\f \x01(\tH\bR\fpoolEndpoint\x88\x01\x01\x12\x14\n" +
	"\x05debug\x18\r \x01(\bR\x05debug\x12%\n" +
	"\vdescription\x18\x0e \x01(\tH\tR\vdescription\x88\x01\x01B\x11\n" +
	"\x0f_read_ahead_maxB\x11\n" +
	"\x0f_read_write_maxB\x06\n" +
	"\x04_uidB\x06\n" +
	"\x04_gidB\x0e\n" +
	"\f_system_userB\x16\n" +
	"\x14_metadata_connectionB\x10\n" +
	"\x0e_io_connectionB\b\n" +
	"\x06_cacheB\x10\n" +
	"\x0e_pool_endpointB\x0e\n" +
	"\f_description\"\xec\x01\n" +
	"\vDAVFSConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x01R\bpassword\x88\x01\x01\x124\n" +
	"\x06config\x18\x04 \x03(\v2\x1c.api.DAVFSConfig.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"G\n" +
	"\tNFSConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xfd\x01\n" +
	"\vMountConfig\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x01 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x02 \x01(\bR\breadOnly\x12#\n" +
	"\rmount_options\x18\x03 \x03(\tR\fmountOptions\x12.\n" +
	"\airodsfs\x18\n" +
	" \x01(\v2\x12.api.IRODSFSConfigH\x00R\airodsfs\x12(\n" +
	"\x05davfs\x18\v \x01(\v2\x10.api.DAVFSConfigH\x00R\x05davfs\x12\"\n" +
	"\x03nfs\x18\f \x01(\v2\x0e.api.NFSConfigH\x00R\x03nfsB\x0f\n" +
	"\rclient_config\"\xc8\x01\n" +
	"\bAPIError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x124\n" +
	"\adetails\x18\x04 \x03(\v2\x1a.api.APIError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x04\n" +
	"\tMountInfo\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\x12%\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0f.api.MountStateR\x05state\x12(\n" +
	"\x06config\x18\x03 \x01(\v2\x10.api.MountConfigR\x06config\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12,\n" +
	"\n" +
	"last_error\x18\x05 \x01(\v2\r.api.APIErrorR\tlastError\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x03R\x03pid\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"mounted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tmountedAt\x12=\n" +
	"\funmounted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vunmountedAt\x12>\n" +
	"\rnext_retry_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\"e\n" +
	"\fMountRequest\x12\x1e\n" +
	"\bmount_id\x18\x01 \x01(\tH\x00R\amountId\x88\x01\x01\x12(\n" +
	"\x06config\x18\x02 \x01(\v2\x10.api.MountConfigR\x06configB\v\n" +
	"\t_mount_id\"5\n" +
	"\rMountResponse\x12$\n" +
	"\x05mount\x18\x01 \x01(\v2\x0e.api.MountInfoR\x05mount\"+\n" +
	"\x0eUnmountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\"7\n" +
	"\x0fUnmountResponse\x12$\n" +
	"\x05mount\x18\x01 \x01(\v2\x0e.api.MountInfoR\x05mount\"\xb9\x01\n" +
	"\x11ListMountsRequest\x12'\n" +
	"\x06states\x18\x01 \x03(\x0e2\x0f.api.MountStateR\x06states\x12/\n" +
	"\x11mount_path_prefix\x18\x02 \x01(\tH\x00R\x0fmountPathPrefix\x88\x01\x01\x12$\n" +
	"\vclient_user\x18\x03 \x01(\tH\x01R\n" +
	"clientUser\x88\x01\x01B\x14\n" +
	"\x12_mount_path_prefixB\x0e\n" +
	"\f_client_user\"<\n" +
	"\x12ListMountsResponse\x12&\n" +
	"\x06mounts\x18\x01 \x03(\v2\x0e.api.MountInfoR\x06mounts\",\n" +
	"\x0fGetMountRequest\x12\x19\n" +
	"\bmount_id\x18\x01 \x01(\tR\amountId\"8\n" +
	"\x10GetMountResponse\x12$\n" +
	"\x05mount\x18\x01 \x01(\v2\x0e.api.MountInfoR\x05mount\"_\n" +
	"\x17WatchMountEventsRequest\x12\x1b\n" +
	"\tmount_ids\x18\x01 \x03(\tR\bmountIds\x12'\n" +
	"\x0finclude_current\x18\x02 \x01(\bR\x0eincludeCurrent\"[\n" +
	"\n" +
	"MountEvent\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.api.MountEventTypeR\x04type\x12$\n" +
	"\x05mount\x18\x02 \x01(\v2\x0e.api.MountInfoR\x05mount*\xec\x01\n" +
	"\n" +
	"MountState\x12\x1b\n" +
	"\x17MOUNT_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MOUNT_STATE_PENDING_MOUNT\x10\x01\x12\x18\n" +
	"\x14MOUNT_STATE_MOUNTING\x10\x02\x12\x17\n" +
	"\x13MOUNT_STATE_MOUNTED\x10\x03\x12\x1f\n" +
	"\x1bMOUNT_STATE_PENDING_UNMOUNT\x10\x04\x12\x1a\n" +
	"\x16MOUNT_STATE_UNMOUNTING\x10\x05\x12\x1a\n" +
	"\x16MOUNT_STATE_RETRY_WAIT\x10\x06\x12\x16\n" +
	"\x12MOUNT_STATE_FAILED\x10\a*\x8d\x01\n" +
	"\x0eMountEventType\x12 \n" +
	"\x1cMOUNT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MOUNT_EVENT_TYPE_SNAPSHOT\x10\x01\x12\x1c\n" +
	"\x18MOUNT_EVENT_TYPE_UPDATED\x10\x02\x12\x1c\n" +
	"\x18MOUNT_EVENT_TYPE_REMOVED\x10\x032\xbb\x02\n" +
	"\fMountService\x120\n" +
	"\x05Mount\x12\x11.api.MountRequest\x1a\x12.api.MountResponse\"\x00\x126\n" +
	"\aUnmount\x12\x13.api.UnmountRequest\x1a\x14.api.UnmountResponse\"\x00\x12?\n" +
	"\n" +
	"ListMounts\x12\x16.api.ListMountsRequest\x1a\x17.api.ListMountsResponse\"\x00\x129\n" +
	"\bGetMount\x12\x14.api.GetMountRequest\x1a\x15.api.GetMountResponse\"\x00\x12E\n" +
	"\x10WatchMountEvents\x12\x1c.api.WatchMountEventsRequest\x1a\x0f.api.MountEvent\"\x000\x01B-Z+github.com/cyverse/irodsfsd/service/api;apib\x06proto3"

var (
	file_service_api_api_proto_rawDescOnce sync.Once
	file_service_api_api_proto_rawDescData []byte
)

func file_service_api_api_proto_rawDescGZIP() []byte {
	file_service_api_api_proto_rawDescOnce.Do(func() {
		file_service_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_api_api_proto_rawDesc), len(file_service_api_api_proto_rawDesc)))
	})
	return file_service_api_api_proto_rawDescData
}

var file_service_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_service_api_api_proto_goTypes = []any{
	(MountState)(0),                     // 0: api.MountState
	(MountEventType)(0),                 // 1: api.MountEventType
	(*Account)(nil),                     // 2: api.Account
	(*PathMapping)(nil),                 // 3: api.PathMapping
	(*ConnectionConfig)(nil),            // 4: api.ConnectionConfig
	(*MetadataCacheTimeoutSetting)(nil), // 5: api.MetadataCacheTimeoutSetting
	(*MemoryBackendConfig)(nil),         // 6: api.MemoryBackendConfig
	(*RistrettoBackendConfig)(nil),      // 7: api.RistrettoBackendConfig
	(*RedisBackendConfig)(nil),          // 8: api.RedisBackendConfig
	(*CacheBackendConfig)(nil),          // 9: api.CacheBackendConfig
	(*CacheConfig)(nil),                 // 10: api.CacheConfig
	(*IRODSFSConfig)(nil),               // 11: api.IRODSFSConfig
	(*DAVFSConfig)(nil),                 // 12: api.DAVFSConfig
	(*NFSConfig)(nil),                   // 13: api.NFSConfig
	(*MountConfig)(nil),                 // 14: api.MountConfig
	(*APIError)(nil),                    // 15: api.APIError
	(*MountInfo)(nil),                   // 16: api.MountInfo
	(*MountRequest)(nil),                // 17: api.MountRequest
	(*MountResponse)(nil),               // 18: api.MountResponse
	(*UnmountRequest)(nil),              // 19: api.UnmountRequest
	(*UnmountResponse)(nil),             // 20: api.UnmountResponse
	(*ListMountsRequest)(nil),           // 21: api.ListMountsRequest
	(*ListMountsResponse)(nil),          // 22: api.ListMountsResponse
	(*GetMountRequest)(nil),             // 23: api.GetMountRequest
	(*GetMountResponse)(nil),            // 24: api.GetMountResponse
	(*WatchMountEventsRequest)(nil),     // 25: api.WatchMountEventsRequest
	(*MountEvent)(nil),                  // 26: api.MountEvent
	nil,                                 // 27: api.DAVFSConfig.ConfigEntry
	nil,                                 // 28: api.APIError.DetailsEntry
	(*durationpb.Duration)(nil),         // 29: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
}
var file_service_api_api_proto_depIdxs = []int32{
	29, // 0: api.ConnectionConfig.creation_timeout:type_name -> google.protobuf.Duration
	29, // 1: api.ConnectionConfig.lifespan:type_name -> google.protobuf.Duration
	29, // 2: api.ConnectionConfig.idle_timeout:type_name -> google.protobuf.Duration
	29, // 3: api.ConnectionConfig.operation_timeout:type_name -> google.protobuf.Duration
	29, // 4: api.ConnectionConfig.long_operation_timeout:type_name -> google.protobuf.Duration
	29, // 5: api.MetadataCacheTimeoutSetting.timeout:type_name -> google.protobuf.Duration
	29, // 6: api.MemoryBackendConfig.cleanup_interval:type_name -> google.protobuf.Duration
	29, // 7: api.MemoryBackendConfig.default_ttl:type_name -> google.protobuf.Duration
	29, // 8: api.RistrettoBackendConfig.default_ttl:type_name -> google.protobuf.Duration
	29, // 9: api.RedisBackendConfig.connect_timeout:type_name -> google.protobuf.Duration
	29, // 10: api.RedisBackendConfig.command_timeout:type_name -> google.protobuf.Duration
	29, // 11: api.RedisBackendConfig.default_ttl:type_name -> google.protobuf.Duration
	6,  // 12: api.CacheBackendConfig.memory:type_name -> api.MemoryBackendConfig
	7,  // 13: api.CacheBackendConfig.ristretto:type_name -> api.RistrettoBackendConfig
	8,  // 14: api.CacheBackendConfig.redis:type_name -> api.RedisBackendConfig
	5,  // 15: api.CacheConfig.metadata_timeout_settings:type_name -> api.MetadataCacheTimeoutSetting
	9,  // 16: api.CacheConfig.backend:type_name -> api.CacheBackendConfig
	2,  // 17: api.IRODSFSConfig.account:type_name -> api.Account
	3,  // 18: api.IRODSFSConfig.path_mappings:type_name -> api.PathMapping
	4,  // 19: api.IRODSFSConfig.metadata_connection:type_name -> api.ConnectionConfig
	4,  // 20: api.IRODSFSConfig.io_connection:type_name -> api.ConnectionConfig
	10, // 21: api.IRODSFSConfig.cache:type_name -> api.CacheConfig
	27, // 22: api.DAVFSConfig.config:type_name -> api.DAVFSConfig.ConfigEntry
	11, // 23: api.MountConfig.irodsfs:type_name -> api.IRODSFSConfig
	12, // 24: api.MountConfig.davfs:type_name -> api.DAVFSConfig
	13, // 25: api.MountConfig.nfs:type_name -> api.NFSConfig
	28, // 26: api.APIError.details:type_name -> api.APIError.DetailsEntry
	0,  // 27: api.MountInfo.state:type_name -> api.MountState
	14, // 28: api.MountInfo.config:type_name -> api.MountConfig
	15, // 29: api.MountInfo.last_error:type_name -> api.APIError
	30, // 30: api.MountInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 31: api.MountInfo.updated_at:type_name -> google.protobuf.Timestamp
	30, // 32: api.MountInfo.mounted_at:type_name -> google.protobuf.Timestamp
	30, // 33: api.MountInfo.unmounted_at:type_name -> google.protobuf.Timestamp
	30, // 34: api.MountInfo.next_retry_at:type_name -> google.protobuf.Timestamp
	14, // 35: api.MountRequest.config:type_name -> api.MountConfig
	16, // 36: api.MountResponse.mount:type_name -> api.MountInfo
	16, // 37: api.UnmountResponse.mount:type_name -> api.MountInfo
	0,  // 38: api.ListMountsRequest.states:type_name -> api.MountState
	16, // 39: api.ListMountsResponse.mounts:type_name -> api.MountInfo
	16, // 40: api.GetMountResponse.mount:type_name -> api.MountInfo
	1,  // 41: api.MountEvent.type:type_name -> api.MountEventType
	16, // 42: api.MountEvent.mount:type_name -> api.MountInfo
	17, // 43: api.MountService.Mount:input_type -> api.MountRequest
	19, // 44: api.MountService.Unmount:input_type -> api.UnmountRequest
	21, // 45: api.MountService.ListMounts:input_type -> api.ListMountsRequest
	23, // 46: api.MountService.GetMount:input_type -> api.GetMountRequest
	25, // 47: api.MountService.WatchMountEvents:input_type -> api.WatchMountEventsRequest
	18, // 48: api.MountService.Mount:output_type -> api.MountResponse
	20, // 49: api.MountService.Unmount:output_type -> api.UnmountResponse
	22, // 50: api.MountService.ListMounts:output_type -> api.ListMountsResponse
	24, // 51: api.MountService.GetMount:output_type -> api.GetMountResponse
	26, // 52: api.MountService.WatchMountEvents:output_type -> api.MountEvent
	48, // [48:53] is the sub-list for method output_type
	43, // [43:48] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_service_api_api_proto_init() }
func file_service_api_api_proto_init() {
	if File_service_api_api_proto != nil {
		return
	}
	file_service_api_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[8].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[12].OneofWrappers = []any{
		(*MountConfig_Irodsfs)(nil),
		(*MountConfig_Davfs)(nil),
		(*MountConfig_Nfs)(nil),
	}
	file_service_api_api_proto_msgTypes[15].OneofWrappers = []any{}
	file_service_api_api_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_api_api_proto_rawDesc), len(file_service_api_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_api_api_proto_goTypes,
		DependencyIndexes: file_service_api_api_proto_depIdxs,
		EnumInfos:         file_service_api_api_proto_enumTypes,
		MessageInfos:      file_service_api_api_proto_msgTypes,
	}.Build()
	File_service_api_api_proto = out.File
	file_service_api_api_proto_goTypes = nil
	file_service_api_api_proto_depIdxs = nil
}
