// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: service/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MountService_Mount_FullMethodName            = "/api.MountService/Mount"
	MountService_Unmount_FullMethodName          = "/api.MountService/Unmount"
	MountService_ListMounts_FullMethodName       = "/api.MountService/ListMounts"
	MountService_GetMount_FullMethodName         = "/api.MountService/GetMount"
	MountService_WatchMountEvents_FullMethodName = "/api.MountService/WatchMountEvents"
)

// MountServiceClient is the client API for MountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MountService manages the complete lifetime of an irodsfs mount. Mount
// creates and starts a mount; Unmount stops it and removes its stored record.
type MountServiceClient interface {
	Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error)
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error)
	ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error)
	GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*GetMountResponse, error)
	WatchMountEvents(ctx context.Context, in *WatchMountEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MountEvent], error)
}

type mountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMountServiceClient(cc grpc.ClientConnInterface) MountServiceClient {
	return &mountServiceClient{cc}
}

func (c *mountServiceClient) Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountResponse)
	err := c.cc.Invoke(ctx, MountService_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mountServiceClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmountResponse)
	err := c.cc.Invoke(ctx, MountService_Unmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mountServiceClient) ListMounts(ctx context.Context, in *ListMountsRequest, opts ...grpc.CallOption) (*ListMountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMountsResponse)
	err := c.cc.Invoke(ctx, MountService_ListMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mountServiceClient) GetMount(ctx context.Context, in *GetMountRequest, opts ...grpc.CallOption) (*GetMountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMountResponse)
	err := c.cc.Invoke(ctx, MountService_GetMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mountServiceClient) WatchMountEvents(ctx context.Context, in *WatchMountEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MountEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MountService_ServiceDesc.Streams[0], MountService_WatchMountEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMountEventsRequest, MountEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MountService_WatchMountEventsClient = grpc.ServerStreamingClient[MountEvent]

// MountServiceServer is the server API for MountService service.
// All implementations must embed UnimplementedMountServiceServer
// for forward compatibility.
//
// MountService manages the complete lifetime of an irodsfs mount. Mount
// creates and starts a mount; Unmount stops it and removes its stored record.
type MountServiceServer interface {
	Mount(context.Context, *MountRequest) (*MountResponse, error)
	Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error)
	ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error)
	GetMount(context.Context, *GetMountRequest) (*GetMountResponse, error)
	WatchMountEvents(*WatchMountEventsRequest, grpc.ServerStreamingServer[MountEvent]) error
	mustEmbedUnimplementedMountServiceServer()
}

// UnimplementedMountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMountServiceServer struct{}

func (UnimplementedMountServiceServer) Mount(context.Context, *MountRequest) (*MountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedMountServiceServer) Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedMountServiceServer) ListMounts(context.Context, *ListMountsRequest) (*ListMountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMounts not implemented")
}
func (UnimplementedMountServiceServer) GetMount(context.Context, *GetMountRequest) (*GetMountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMount not implemented")
}
func (UnimplementedMountServiceServer) WatchMountEvents(*WatchMountEventsRequest, grpc.ServerStreamingServer[MountEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchMountEvents not implemented")
}
func (UnimplementedMountServiceServer) mustEmbedUnimplementedMountServiceServer() {}
func (UnimplementedMountServiceServer) testEmbeddedByValue()                      {}

// UnsafeMountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MountServiceServer will
// result in compilation errors.
type UnsafeMountServiceServer interface {
	mustEmbedUnimplementedMountServiceServer()
}

func RegisterMountServiceServer(s grpc.ServiceRegistrar, srv MountServiceServer) {
	// If the following call panics, it indicates UnimplementedMountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MountService_ServiceDesc, srv)
}

func _MountService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MountServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MountService_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MountServiceServer).Mount(ctx, req.(*MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MountService_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MountServiceServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MountService_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MountServiceServer).Unmount(ctx, req.(*UnmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MountService_ListMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MountServiceServer).ListMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MountService_ListMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MountServiceServer).ListMounts(ctx, req.(*ListMountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MountService_GetMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MountServiceServer).GetMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MountService_GetMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MountServiceServer).GetMount(ctx, req.(*GetMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MountService_WatchMountEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMountEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MountServiceServer).WatchMountEvents(m, &grpc.GenericServerStream[WatchMountEventsRequest, MountEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MountService_WatchMountEventsServer = grpc.ServerStreamingServer[MountEvent]

// MountService_ServiceDesc is the grpc.ServiceDesc for MountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MountService",
	HandlerType: (*MountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mount",
			Handler:    _MountService_Mount_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _MountService_Unmount_Handler,
		},
		{
			MethodName: "ListMounts",
			Handler:    _MountService_ListMounts_Handler,
		},
		{
			MethodName: "GetMount",
			Handler:    _MountService_GetMount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMountEvents",
			Handler:       _MountService_WatchMountEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/api/api.proto",
}
